services:
    db:
        container_name: db
        build:
            dockerfile: docker/postgres/Dockerfile
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_storage:/var/lib/postgresql/data
            - ./ops/script/init_db.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=i2canfly_
            - POSTGRES_USER=konst
            - POSTGRES_DB=bubbledb
            - PGDATA=/var/lib/postgresql/data/pgdata

    web:
        container_name: web
        build:
            dockerfile: docker/web/Dockerfile
        ports:
            - "8000:8000"

    # qdrant:
    #     container_name: qdrant
    #     image: qdrant/qdrant
    #     ports:
    #         - "6333:6333"
    #     volumes:
    #         - ./qdrant_storage:/qdrant/storage
