services:
    db:
        container_name: db
        build:
            dockerfile: docker/postgres/Dockerfile
        image: 246532218018.dkr.ecr.eu-central-1.amazonaws.com/postgres-bubble:latest
        platform: ${PLATFORM}
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_storage:/var/lib/postgresql/data
            - ./ops/script/init_db.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=i2canfly_
            - POSTGRES_USER=konst
            - POSTGRES_DB=bubbledb
            - PGDATA=/var/lib/postgresql/data/pgdata

    web:
        container_name: web
        build:
            dockerfile: docker/web/Dockerfile
        image: 246532218018.dkr.ecr.eu-central-1.amazonaws.com/fastapi-bubble:latest
        platform: ${PLATFORM}
        ports:
            - "8000:8000"

    ingester:
        container_name: ingester
        build:
            dockerfile: docker/ingester/Dockerfile
        image: 246532218018.dkr.ecr.eu-central-1.amazonaws.com/ingester-bubble:latest
        platform: ${PLATFORM}
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://konst:i2canfly_@db:5432/bubbledb

    # qdrant:
    #     container_name: qdrant
    #     image: qdrant/qdrant
    #     ports:
    #         - "6333:6333"
    #     volumes:
    #         - ./qdrant_storage:/qdrant/storage
